[phases.setup]
nixPkgs = ['python311', 'libGL', 'glib']

[phases.install]
cmds = ['pip install --upgrade pip', 'pip install -r requirements.txt']

[start]
cmd = 'gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120'
